name: Cron Integration Test

# Controls when the workflow will run
on:
  push:
    branches: [ "main", "branch-*" ]
  pull_request:
    branches: [ "main", "branch-*" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # Integration test for AMD64 architecture
  test-amd64-arch:
    needs: changes
    if: needs.changes.outputs.source_changes == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      matrix:
        architecture: [linux/amd64]
        java-version: [ 8, 11, 17 ]
        test-mode: [ embedded, deploy ]
    env:
      DOCKER_RUN_NAME: hive-amd64
      PLATFORM: ${{ matrix.architecture }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'gradle'


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Package Gravitino
        run: |
          ./gradlew compileDistribution -x test -PjdkVersion=${{ matrix.java-version }}

      - name: Setup debug Github Action
        if: ${{ contains(github.event.pull_request.labels.*.name, 'debug action') }}
        uses: csexton/debugger-action@master

      - name: Free up disk space
        run: |
          dev/ci/util_free_space.sh

      - name: Integration Test
        id: integrationTest
        run: |
          ./gradlew test -PskipTests -PtestMode=${{ matrix.test-mode }} -PjdkVersion=${{ matrix.java-version }}

      - name: Upload integrate tests reports
        uses: actions/upload-artifact@v3
        if: ${{ failure() && steps.integrationTest.outcome == 'failure' }}
        with:
          name: integrate test reports
          path: |
            build/reports
            integration-test/build/*.log
            integration-test/build/*.tar
            integration-test/build/trino-ci-container-log/hive/*.*
            integration-test/build/trino-ci-container-log/hdfs/*.*
            distribution/package/logs/gravitino-server.out
            distribution/package/logs/gravitino-server.log
            catalogs/**/*.log
            catalogs/**/*.tar
            distribution/**/*.log
            spark-connector/v3.3/spark/build/spark-3.3-integration-test.log
            spark-connector/v3.4/spark/build/spark-3.4-integration-test.log
            spark-connector/v3.5/spark/build/spark-3.5-integration-test.log
            flink-connector/build/flink-connector-integration-test.log
            flink-connector/build/*.tar
